let jug1= new JugadorCampo("Juan", new Date(), Posiciones.DELANTERO, "CABA", new Set<Equipo>, 5, 20, 10, 10)
let jug2= new JugadorCampo("Jose", new Date(), Posiciones.DELANTERO, "CABA", new Set<Equipo>, 7, 2, 9, 2)
let jug3= new JugadorCampo("Lucas", new Date(), Posiciones.DELANTERO, "CABA", new Set<Equipo>, 5, 20, 5, 7)
let jug4= new JugadorCampo("Ian", new Date(), Posiciones.DELANTERO, "CABA", new Set<Equipo>, 5, 20, 2, 8)
let arq1= new Arquero("Mateo", new Date(), "CABA", new Set<Equipo>, 1, 0, 41)

let jug5= new JugadorCampo("Julian", new Date(), Posiciones.DELANTERO, "CABA", new Set<Equipo>, 9, 20, 9, 0)
let jug6= new JugadorCampo("Ciro", new Date(), Posiciones.DELANTERO, "CABA", new Set<Equipo>, 5, 4, 15, 8)
let jug7= new JugadorCampo("Thiago", new Date(), Posiciones.DELANTERO, "CABA", new Set<Equipo>, 2, 20, 34, 10)
let jug8= new JugadorCampo("Ian", new Date(), Posiciones.DELANTERO, "CABA", new Set<Equipo>, 5, 7, 12, 1)
let arq2= new Arquero("Santi", new Date(), "CABA", new Set<Equipo>, 2, 56, 2)

let equipo1= new Equipo("Panchieri", new Set<Jugador>, new Set<Partido>)
equipo1.getJugadores.add(jug1)
equipo1.getJugadores.add(jug2)
equipo1.getJugadores.add(jug3)
equipo1.getJugadores.add(jug4)
equipo1.getJugadores.add(arq1)

let equipo2= new Equipo("Dorsalo", new Set<Jugador>, new Set<Partido>)
equipo2.getJugadores.add(jug5)
equipo2.getJugadores.add(jug6)
equipo2.getJugadores.add(jug7)
equipo2.getJugadores.add(jug8)
equipo2.getJugadores.add(arq2)